apiVersion: apps/v1
kind: Deployment
metadata:
  name: usher-app
spec:
  selector:
    matchLabels:
      app: usher
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: usher
        tier: frontend
    spec:
      containers:
      - name: usher
        image: usher:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "150Mi"
            cpu: "250m"