apiVersion: v1
kind: Service
metadata:
  name: usher-lb-svc
  labels:
    app: usher
spec:
  selector:
    app: usher
    tier: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000